### ISSUE TITLE
4K图片测试报错

### ISSUE THREAD

**Issue by zhs1** [iii935/HDCFM#1]
您好，我在4K图上测试会报错：cudaCheckError() failed : invalid configuration argument，但是在1080p图上测试没问题，这是什么原因呢？此外，请问您方便公开预训练模型吗？

**Comment by kepengxu** [comment]
When you encounter the "invalid configuration argument" error during CUDA operations, it's often related to how you've configured your kernel launch parameters. This can encompass a range of issues from how you've set your block sizes, grid sizes, or how you're accessing memory within the kernel.

Here's a checklist to help you troubleshoot the issue:

Thread and Block Dimensions:

Ensure that the number of threads per block does not exceed the maximum allowed (1024 threads for most GPUs).
Ensure that the dimensions of the grid () and block () make sense for your problem size.dimGriddimBlock
Resource Limits:

Make sure you are not using more shared memory per block than available.
Make sure the number of registers used by your kernel does not exceed the limit.
You can check these specifications using NVIDIA's  compiler with the  flag.nvcc--ptxas-options=-v
Memory Access:

Check for out-of-bounds memory accesses in your kernel. This can be done using tools like .cuda-memcheck
Kernel Launch:

Ensure the kernel launch itself is correctly specified. An incorrect launch configuration might not throw an error until a subsequent CUDA API call is made, which can be misleading.
Previous Errors:

Make sure that previous CUDA operations did not produce an error. The error might not manifest until a subsequent CUDA call is made. Therefore, frequently checking for errors can be helpful. For example, by inserting  after significant CUDA API calls.cudaCheckError()
Check Device Capabilities:

Make sure you're not trying to use a feature of a newer Compute Capability on an older GPU.
Use CUDA Debugging Tools:

Tools like , NVIDIA Nsight, and the NVIDIA Visual Profiler can provide additional insight into what might be causing the error.cuda-memcheck
Update CUDA:

Sometimes there can be bugs in certain versions of the CUDA toolkit. If you're not on the latest version, consider updating.
Simplified Test Case:

Try to simplify your kernel to the bare minimum that reproduces the problem. This can often illuminate what the actual problem is.
Documentation and Forums:

Check NVIDIA's official documentation or forums like NVIDIA Developer forums for similar issues.
Remember that CUDA operations are asynchronous, meaning the error might not originate from where you think it does. It's often a good idea to insert  before checking errors to make sure that all prior CUDA operations have completed.cudaDeviceSynchronize()

Lastly, if you're still struggling to identify the issue, you might find it helpful to provide a minimal reproducible code example for others to help you troubleshoot.


我推测是DDF的cuda分块等参数设置问题导致的，可以尝试修改DDFcuda实现中的分块线程数量再编译（具体设置取决于您使用用的显卡和cuda版本）

预训练模型后续会发布

如您还有任何问题欢迎添加vx及时沟通：xukepeng1234

**Comment by kepengxu** [comment]
the pretrain weights is releaseed @zhs1
